### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by brycebaril** [yaronn/blessed-contrib#1]
Noticed there is no license on this -- any plans for what direction you might take there?

As it stands it's ambiguous if one could even use it for private stuff.

**Comment by whatsim** [comment]
+1

**Comment by yaronn** [comment]
I have added the MIT license to the readme, thanks!

**Comment by brycebaril** [comment]
Great! Thank you much!

Excited to play around, the example dashboard looks fantastic. :smile_cat:

**Comment by waldyrious** [comment]
> I have added the MIT license to the readme, thanks!

Just for future reference, that was done in https://github.com/yaronn/blessed-contrib/pull/59.

**Comment by lirantal** [comment]
Indeed, thanks @waldyrious
