### ISSUE TITLE
Doesn't resize widgets on SIGWINCH

### ISSUE THREAD

**Issue by mgedmin** [yaronn/blessed-contrib#10]
1. Launch the demo in a 80x24 terminal
2. Maximize the terminal

You end up with this:
![ekrano nuotrauka is 2015-01-16 12 51 08](https://cloud.githubusercontent.com/assets/159967/5775100/5fb28ebc-9d7e-11e4-97ba-f5e9e6389b01.png)

**Comment by yaronn** [comment]
thanks, this is a known issue. the solution needs to be to listen to the screen object "resize" event and then create all the dashboard again. I'll leave this issue open.

**Comment by ArthurXHK** [comment]
all work except `lcdLineOne` in my Mac terminal. T_T
