### ISSUE TITLE
Direction of Line Chart

### ISSUE THREAD

**Issue by davidgatti** [yaronn/blessed-contrib#101]
Quick question: is it possible to set the direction of the line chart? Because right now it is going from left to right, and I would like to have to from right to left.

**Comment by yaronn** [comment]
The Y axis is currently always on the left. Probably not too hard to change it to the right but requires some investigation. The line itself is neutral and does not care in which "direction" its values are so if the axis position does not matter to you (or you are ok with removing it all together) you can try it.

**Comment by davidgatti** [comment]
Hmm I think I didn't do a good job of explaining myself, one more time :) In your examples I see that the line graph, is being drawn from the right to the left moving in this direction <----

But when I do it the graph moves from the left to the right like so --->

Here is a short movie that I took https://www.instagram.com/p/BRjl6XAAQ6L to better show what I'm talking about.

So now I'm wondering, is the direction something you set in your module, or the way that I fill the Array with data?

**Comment by yaronn** [comment]
there is no setting, it is determined by the array of data. I assume initially you supply the values only to the left part of the graph and gradually give more values. you can check examples/dashboard.js to see my example code.

**Comment by davidgatti** [comment]
OO, ok, got it now :) thank you for the hint :)
