### ISSUE TITLE
Dose log support new line?

### ISSUE THREAD

**Issue by davidgatti** [yaronn/blessed-contrib#102]
I'm working on my little project and I run in this situation where it seams the `log` module doesn't support new line characters, is this true? Or did I miss a setting in the `log` module? 

When I remove the new line characters I can see everything in one line. Of course I have no problem splitting the string, and call the log module on each element of the array, but I wonder if I have to make such work around.

**Comment by yaronn** [comment]
it probably doesn't since it is based on blessed#list which has a list semantics so no new lines. Your workaround seems the right way now.

**Comment by davidgatti** [comment]
Got it, and thank you :)
