### ISSUE TITLE
Is this a fork of "blessed"?

### ISSUE THREAD

**Issue by JHGitty** [yaronn/blessed-contrib#104]
Is this project named "blessed-contrib" a fork of "blessed"?

If yes: Are the latest changes of "blessed" from late 2015 / begin of 2016 inside "blessed-contrib"?

I opened the same question on the "blessed" github issue tracker,
please answer it also there: https://github.com/chjj/blessed/issues/293

**Comment by pt300** [comment]
I'm sure README should resolve your concerns regarding this repo.

**Comment by lirantal** [comment]
In short: it's not.
