### ISSUE TITLE
fork blessed, maintain?

### ISSUE THREAD

**Issue by rattrayalex** [yaronn/blessed-contrib#128]
https://github.com/chjj/blessed/issues/293 indicates blessed is unmaintained. @laurent suggested that maintainers here might be willing to fork blessed and maintain it. 

Thoughts?

**Comment by yaronn** [comment]
Sorry but I probably don't have the capacity at the moment to do this.

**Comment by rattrayalex** [comment]
Cool, definitely fair. Looking at the contributors tab on this repo, it doesn't seem that there would be any candidates there, either. Closing.
