### ISSUE TITLE
Releasing an updated npm package version

### ISSUE THREAD

**Issue by lirantal** [yaronn/blessed-contrib#149]
@yaronn thanks for inviting me to the project ❤️ 

can you also invite me to the npmjs project at https://www.npmjs.com/package/blessed-contrib with publish access so I can release new versions with the updates we added to the github repo?

My npmjs user is [lirantal](https://www.npmjs.com/~lirantal)

**Comment by yaronn** [comment]
done!

**Comment by binarymist** [comment]
Keep us posted on when you `publish` @lirantal Thanks.

**Comment by lirantal** [comment]
Thanks @yaronn!

@binarymist 4.8.6 released https://github.com/yaronn/blessed-contrib/commit/1e896e4ccc73e8db3ec0244d28069038b07daed1

**Comment by binarymist** [comment]
Thanks @lirantal . Now we have a problem with the dependency on picture-tube@1.0.0 › request@2.9.203
See: https://snyk.io/test/github/purpleteam-labs/purpleteam?targetFile=package.json
Do you also have contributing privs on picture-tube?

**Comment by binarymist** [comment]
https://github.com/substack/picture-tube/issues/13
https://github.com/substack/picture-tube/pull/12

**Comment by binarymist** [comment]
How do we want to deal with this? Somehow I doubt substack will be able to deal with this amongst his 930  repos. I remember him doing talks years ago about "everyone should write loads of packages and just publish them to npm"
