### ISSUE TITLE
Were do i start?

### ISSUE THREAD

**Issue by SAUCYSOUP76** [yaronn/blessed-contrib#159]
I have no idea on were to start to create my own anyone got any tips?

**Comment by lirantal** [comment]
Hi @SAUCYSOUP76,

Some ideas to get you started:
1. There's an [examples](https://github.com/yaronn/blessed-contrib/tree/master/examples) directory you can look at
2. Take some inspirations from [projects](https://www.npmjs.com/package/blessed-contrib) that depend on blessed-contrib

**Comment by SAUCYSOUP76** [comment]
Thanks just thinking this would be great to create a modern bulletin board system.

**Comment by lirantal** [comment]
Go for it!
