### ISSUE TITLE
NodeJs version(s)

### ISSUE THREAD

**Issue by cgoea** [yaronn/blessed-contrib#175]
Hello,

What a nice little library! Thank you for coding this and sharing it with the world.

What NodeJs versions is this module most compatible with? In other words, under which NodeJs versions is blessed-contrib known to work flawlessly and which versions should be avoided?

Thanks.

**Comment by lirantal** [comment]
You should strive to work with Node.js LTS which is currently 10

**Comment by cgoea** [comment]
Thank you @lirantal.

**Comment by lirantal** [comment]
Sure thing. Have fun with blessed!
