### ISSUE TITLE
Lines appear with letters

### ISSUE THREAD

**Issue by perfaram** [yaronn/blessed-contrib#18]
The separating lines (the ones that make a box around a widget) do not appear with dashes (as they do in your screenshot) but with the letters 'q', 'm', 'x', 'j', 'k', and 'l'.
Any idea ? I don't think it is related to encoding...

EDIT : Just test with another Terminal (OSX 10.10) settings, and it's the exact same thing

**Comment by yaronn** [comment]
I think it is an issue with the blessed project itself. Can you try the simplest blessed sample and see if this is the same?

https://github.com/chjj/blessed

**Comment by perfaram** [comment]
Running the "widget" example from blessed shows me the same letter. Gonna close the issue and open one one chjj/blessed !
Thanks for your help :smile:
