### ISSUE TITLE
how to set focus border fg ?

### ISSUE THREAD

**Issue by yyjjqq94** [yaronn/blessed-contrib#197]
grid.set(0, 0, 2, 5, tree, {
    showNthLabel: 1,
    maxY: 100,
    label: 'Pkg',
    showLegend: true,
    style: {
        focus: {
            border: {
                fg: 'red'
            }
        }
   }
});

Maximum call stack size exceeded

**Comment by Pandaphobic** [comment]
How'd you get this working?
