### ISSUE TITLE
Map widget is squashed

### ISSUE THREAD

**Issue by vladikoff** [yaronn/blessed-contrib#2]
Hey, great project! 
I ran the demo and got this result:
![](http://v14d.com/i/54b70507e5fcc.jpg)

Seems like the map graphic is squashed. I'm using ZSH.

**Comment by yaronn** [comment]
Thanks!
What os you use and what screen resolution?

**Comment by vladikoff** [comment]
OS X 10.9.5 on MBP Retina
1680 x 1050

**Comment by alfredbez** [comment]
OS X 10.10.1 on iMac
2560 x 1440

iTerm
![screenshot 2015-01-15 16 08 47](https://cloud.githubusercontent.com/assets/1001186/5759900/5b21d310-9cd1-11e4-9523-9a82cf7630cd.png)
Terminal
![screenshot 2015-01-15 16 12 14](https://cloud.githubusercontent.com/assets/1001186/5759901/5b269bc0-9cd1-11e4-8b7f-3ae2e121f28c.png)

**Comment by yaronn** [comment]
thanks @alfredbez 

@vladikoff - can you try the terminal?

**Comment by vladikoff** [comment]
I'm using Terminal

**Comment by yaronn** [comment]
Try this example (you can also adjust width and height). Let's see if the problem is with the dashboard sample or even with a standalone map.

   npm install blessed blessed-contrib

    var blessed = require('blessed')
         , contrib = require('blessed-contrib')
         , screen = blessed.screen()
         , map = contrib.map({width: 100, height: 30})
       screen.append(map)

       screen.key(['escape', 'q', 'C-c'], function(ch, key) {
         return process.exit(0);
       });

       screen.render()
