### ISSUE TITLE
Broken dependency "marked-terminal" + "marked" when using `strict-peer-dependencies`

### ISSUE THREAD

**Issue by prescience-data** [yaronn/blessed-contrib#209]
After installing in a downstream package, I just now started receiving a peer dependency error:

```error
blessed-contrib: marked-terminal@4.1.1 requires a peer of marked@^1.0.0 || ^2.0.0 but version 0.7.0 was installed.
```
### package.json:
https://github.com/yaronn/blessed-contrib/blob/master/package.json#L35

### causal upstream commit:
https://github.com/mikaelbr/marked-terminal/commit/abba40b6d0150c591ca92a6ec70c5c0103c41a4a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

The `marked-terminal` requires a peer dependency of `"marked": "^1.x.x || ^2.x.x"`, whereas `blessed-contrib` is only installing `"marked": "^0.x.x"`

![image](https://user-images.githubusercontent.com/65471523/109862621-c2421400-7cb4-11eb-97b6-4468c8fe0eb4.png)

Not a problem if not using `strict-peer-dependencies` but for projects that require this (for whatever reason) it makes it `FAIL` instead of `WARN` which blocks installation of `fastify-cli`.

![image](https://user-images.githubusercontent.com/65471523/109863495-cf133780-7cb5-11eb-8223-501ed7ae0eb5.png)

**Comment by Israel-Laguan** [comment]
I also have this issue using `nodejs-dashboard`, please merge https://github.com/yaronn/blessed-contrib/pull/229

**Comment by lirantal** [comment]
@Israel-Laguan new version published got released, do you want to take another test here?

**Comment by Israel-Laguan** [comment]
Tested and worked fine now, thanks for the hard work!

**Comment by lirantal** [comment]
That's great to hear!
