### ISSUE TITLE
Line characters not working

### ISSUE THREAD

**Issue by jscheel** [yaronn/blessed-contrib#3]
OSX 10.9.5
used iterm2 and terminal

![screen shot 2015-01-14 at 10 03 50 pm](https://cloud.githubusercontent.com/assets/211478/5752390/b28af6a6-9c39-11e4-9465-d584f32ef9cb.png)

**Comment by yaronn** [comment]
Can you try the first example in the blessed project readme? Want to know
if this is a blessed or blessed-contrib issue.

**Comment by jscheel** [comment]
Ah, appears to be an issue with blessed. I'll file there. Thanks!
