### ISSUE TITLE
Why is `blessed` a dev dependency as opposed to a normal dependency?

### ISSUE THREAD

**Issue by mjkaufer** [yaronn/blessed-contrib#31]
If there's no real reason, can I send a PR to make `blessed` a normal dependency? I tried to `npm install blessed-contrib` but I couldn't run the example off the bat because I had to install `blessed`.

**Comment by yaronn** [comment]
Hi @mjkaufer 

blessed-contrib is sort of a plugin for blessed but does not directly depend on it. The example is not part of blessed-contrib core (if you install blessed-contrib you will not need the sample). That is why the README recommends to install blessed before running the sample. This is a good point though: blessed could be considered a peer dependency of blessed-contrib (http://blog.nodejs.org/2013/02/07/peer-dependencies/) so any PR on this is welcome!

**Comment by piranna** [comment]
+1 to PeerDependency, I have put them in both peerDependencies (for production) and devDependencies (for testing) without problems.

**Comment by yaronn** [comment]
added blessed as peer dependency
