### ISSUE TITLE
Allow to change sparkline heading colours.

### ISSUE THREAD

**Issue by BorisKourt** [yaronn/blessed-contrib#34]
Currently some terminal themes can render them as the background colour. But it doesn't seem like I can change the text colour, only the sparkline bar colour.

**Comment by yaronn** [comment]
Hן @BorisKourt 

I have just added support for this:

    grid2.set(1, 0, 1, 1, contrib.sparkline, 
      { label: 'Throughput (bits/sec)'
      , tags: true
      , style: { fg: 'blue', titleFg: 'white' }})


enjoy :)

**Comment by BorisKourt** [comment]
Thank you @yaronn!
