### ISSUE TITLE
Am not able to Run the Demo in Window 

### ISSUE THREAD

**Issue by fre0k** [yaronn/blessed-contrib#37]
I'm not able to run demo @yaronn @aruntakkar

**Comment by yaronn** [comment]
Hi @aruntakkar 

the default dashboard uses braille character and does not run on windows yet. it will actually run on your windows if you have the braille fonts installed, but I still didn't find where to get them if you don't.
however it is strange that you see no results - you should at least see some characters. do you get any error?

**Comment by aruntakkar** [comment]
![image](https://cloud.githubusercontent.com/assets/9693884/6896414/ba610d7a-d708-11e4-8dac-5c8c76519d0c.png)

Error When i try to Run in Node

**Comment by yaronn** [comment]
Did you run npm install?

**Comment by aruntakkar** [comment]
![image](https://cloud.githubusercontent.com/assets/9693884/6903915/f7612516-d73a-11e4-82df-d14db169dac4.png)
Screen with npm install and Now i Have Braille Character install for my Machine.

**Comment by aruntakkar** [comment]
![image](https://cloud.githubusercontent.com/assets/9693884/6903955/4178c4c4-d73b-11e4-88f5-d97624781740.png)
Screen when try to Run npm install(these Command Purpose?)Now I have also install the Braille Fonts in my Machine.

**Comment by tracker1** [comment]
Are the braille fonts free/open... maybe a pre-install script on windows could attempt to download/install them.. or at least notify.

Would be possible to create a separate npm package that does this, but that would require running in an admin console.

**Comment by yaronn** [comment]
Arun - what do you see now when you run the dashboard?

Michael - I didn't find where to get them from but I heard someone which
had them built in by his corporate image so I know they exist somewhere...

**Comment by aruntakkar** [comment]
![image](https://cloud.githubusercontent.com/assets/9693884/6910968/13dea9c4-d778-11e4-880b-f593b0a27521.png)
Screen When Try to Run the Dashboard.js 
And i Get the Fonts From [Link](http://www.dafont.com/braille.font)

**Comment by yaronn** [comment]
@aruntakkar - I think you have attached a wrong picture. I have also installed those fonts from the link but when I run:

    cmd
    SET TERM=windows-ansi
    console.log(String.fromCharCode(0x2809))

I see a question mark and not the braille characters. How were you able to see braille?

**Comment by aruntakkar** [comment]
am not able to see anything When i try to install the fonts again from the link and downloaded the fonts window says fonts installed. So What to Do ?

**Comment by yaronn** [comment]
unfortunately I am still not sure how to see those fonts on windows.
nevertheolss you  should still see something (even if question marks). can you send me a screen shot of what you see when you run dashboard.js?

**Comment by aruntakkar** [comment]
![image](https://cloud.githubusercontent.com/assets/9693884/6920722/e0953270-d7dd-11e4-86cf-f28a6b8611c9.png)
Screen Shot is Similar To Previous.

**Comment by yaronn** [comment]
do you have a file c:\Users\hp\examples\dashboard.js   ?  maybe the clone did not work correctly?

**Comment by aruntakkar** [comment]
Can i Use dashboard in these Way Same Error.

**Comment by yaronn** [comment]
from what I know there is a problem in windows with the braile font. there is a way to install it but I am not sure what it is.
you seem to have an additional problem even before that - do you have a file c:\Users\hp\examples\dashboard.js  ?

**Comment by aruntakkar** [comment]
Yes I Have a File and I Tried all the Suggested Way By  you and i manually Checked the File and Clone the Repo more than 3 times. IF i Find a Solution for these Problem i Will Inform you.

**Comment by yaronn** [comment]
ok, sorry I could not help.
try cd c:\Users\hp\examples  and then run node dashboard.js from there

**Comment by yednaps** [comment]
Hi @aruntakkar, I was able to get the example dashboard running in Windows without too much trouble. I installed node using the windows installer from the node downloads page (node-v0.12.1-x64.msi), cloned the blessed-contrib repo and followed the install instructions. Note that I did not find a suitable Braille font so all characters come up as "?" and the dashboard may not look as good.

![b-c_win](https://cloud.githubusercontent.com/assets/1047967/6930765/0dc59654-d7bb-11e4-9acc-77dc6ee4f3bc.PNG)

It could be that the way the relative path to dashboard.js is shown in the instructions ("./examples/dashboard.js") does not work in Windows, so you may need to cd into the examples directory or specify the complete path to your dashboard.js file when you try to run it (i.e. run "node c:\Users\hp\examples\dashboard.js")

**Comment by aruntakkar** [comment]
@yaronn am on Window 7 32 bit Version Here's the Screen 
![image](https://cloud.githubusercontent.com/assets/9693884/6959425/6aa592b2-d936-11e4-9a1b-611fda61e39e.png) Same Error as Previous.

**Comment by yaronn** [comment]
when you run "npm install" to do you get success or error?

**Comment by yaronn** [comment]
also, in file /lib/widget/picture.js try to put this line in comment: 

    , pictureTube = require('picture-tube')

**Comment by popey456963** [comment]
@aruntakkar Your problem was you were running node ../examples/dashboard.js.  The .. goes up a directory, you just wanted to stay in the same directory, so ./examples/dashboard.js would have sufficed.

Any news on better Windows support though?  At the moment depending on the browser you use you get varying degrees of success:

Powershell:
![](https://puu.sh/sBWBZ/a32a6df9db.png)

Cmder:
![](https://puu.sh/sBWtN/71178f778b.png)

Command Prompt:
![](https://puu.sh/sBWBG/a538cbb135.png)

I see people suggesting installing a braille font, any ideas which one?

**Comment by popey456963** [comment]
Oops, got it to work with a braille font & setting the term.  Was going to report back here but apparently some intelligent individual already did it and I was blind enough to not see it in the README.  Future people, look at [this](http://webservices20.blogspot.co.uk/2015/04/running-terminal-dashboards-on-windows.html).
