### ISSUE TITLE
Nothing happens when I run

### ISSUE THREAD

**Issue by frodopwns** [yaronn/blessed-contrib#4]
Cloned the repo
sudo apt-get install npm
sudo apt-get install node
npm install
node ./examples/dashboard.js

and nothing happens

Running Ubuntu 14.04

**Comment by yaronn** [comment]
Can you check if node is installed properly by running an hello world?

**Comment by stevelacy** [comment]
@frodopwns if you installed node via apt-get it may not have installed the executable to `node`, but rather `nodejs`

**Comment by alfredbez** [comment]
@frodopwns what is the output from `$ node --version`

As mentioned [here](https://github.com/joyent/node/wiki/installing-node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions) and @stevelacy already said, you need to install nodejs.

According to [this stackoverflow answer](http://stackoverflow.com/a/18130296/2123108) you can also symlink nodejs to node

**Comment by frodopwns** [comment]
I did a 

    sudo apt-get install nodejs

and then attempted to run:

    node ./examples/dashboard.js
    The program 'node' can be found in the following packages:  
    * node
    * nodejs-legacy

So I installed 

    sudo apt-get install nodejs-legacy

And everything started working. Thanks guys.

**Comment by stevelacy** [comment]
@frodopwns just for future info: I always compile my node install from source. It leaves a clean system with the executable of `node`

**Comment by frodopwns** [comment]
@stevelacy I don;t normally use node but this project caught my attention.  First time running node actually :-). Thanks for the info.

**Comment by stevelacy** [comment]
Welcome to the dark side :)

**Comment by lesterzone** [comment]
Just as reference about installing nodejs https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions

**Comment by jofftiquez** [comment]
installing `nodejs-legacy` fixed the problem
