### ISSUE TITLE
Select Events on Table Widget

### ISSUE THREAD

**Issue by simonalbrecht** [yaronn/blessed-contrib#41]
Is it possible to implement the select events on the table widget? At the moment, the widget does not emit any events at all from what I can tell.

**Comment by yaronn** [comment]
there is a workaround: internally the table uses a blessed list to represent the rows.
so table.rows is a blessed list (https://github.com/chjj/blessed#list-from-box) and emits its 'select' event.

**Comment by yaronn** [comment]
there is a workaround: internally the table uses a blessed list to represent the rows.
so table.rows is a blessed list (https://github.com/chjj/blessed#list-from-box) and emits its 'select' event.

**Comment by simonalbrecht** [comment]
I will try this tomorrow, thanks!

**Comment by Aaaaaashu** [comment]
@simonalbrecht 
Hey, How do you solve this problem？

**Comment by simonalbrecht** [comment]
@Aaaaaashu I actually did not find a solution and opted to use blessed directly.

**Comment by Aaaaaashu** [comment]
@simonalbrecht 
`table.row` resolve this problem!

```
table.rows.on('select', (item, index) => {
  console.log(item, index);
 })
```

**Comment by 4sh3** [comment]
how can I access to the values of an item??

**Comment by fiacc** [comment]
event seems to be `select item` now

**Comment by KaKi87** [comment]
Hello @simonalbrecht could you share the code you used to implement this table without `contrib-blessed` ? I can't figure out this [table.js](https://github.com/yaronn/blessed-contrib/blob/master/lib/widget/table.js) file... Thanks
