### ISSUE TITLE
Support color and font tags in log?

### ISSUE THREAD

**Issue by jwhitlark** [yaronn/blessed-contrib#42]
I was hoping to color some lines based on content.  Reading the blessed docs, it seems like I might be able to do something like "{red-fg}foo{/red-fg}", but this doesn't work.  I guess I could just use terminal escape codes, but I'm not positive that those wouldn't have a negative impact somewhere.

Any ideas?

**Comment by jwhitlark** [comment]
I tried the colors library, at https://www.npmjs.com/package/colors, and it works, mostly...

var colors = require('colors/safe');

log.push(colors.red('hello')); works, except as the last line.  (This might be some artifact because I'm actually doing all this through Clojurescript).

**Comment by yaronn** [comment]
yes, this is a good approach. I will add interactive=false internally in the component so it will always behave correctly. thanks!
