### ISSUE TITLE
Table widget doesn't allow you to set most options.

### ISSUE THREAD

**Issue by jwhitlark** [yaronn/blessed-contrib#43]
keys, fg, interactive, selectedFg, selectedBg, etc. are set to defaults.  There doesn't appear to be any way to override them if you don't want the default colors, or don't want the selection highlighted.

Or have I missed something?

**Comment by yaronn** [comment]
Hi

I have added this support:

https://github.com/yaronn/blessed-contrib#table

On Tue, Apr 14, 2015 at 1:11 AM, jwhitlark <notifications@github.com> wrote:

> keys, fg, interactive, selectedFg, selectedBg, etc. are set to defaults.
> There doesn't appear to be any way to override them if you don't want the
> default colors, or don't want the selection highlighted.
>
> Or have I missed something?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yaronn/blessed-contrib/issues/43>.
>



-- 

I'm on Twitter (@YaronNaveh <http://twitter.com/#!/YaronNaveh>)

**Comment by jwhitlark** [comment]
Too old.
