### ISSUE TITLE
grid.set purges function values from options

### ISSUE THREAD

**Issue by algernon** [yaronn/blessed-contrib#47]
[This line](https://github.com/yaronn/blessed-contrib/blob/550f460bd16e5452672946cfaada1c0b1f53d14a/lib/layout/grid.js#L24) in [lib/layout/grid.js](https://github.com/yaronn/blessed-contrib/blob/master/lib/layout/grid.js) removes keys from the options that have function values. As far as see from the history of the file, this was introduced in 9f73971c, and was not present before.

This causes a few problems for me, because I have custom widgets built on top of blessed-contrib, that would really benefit from being able to specify callback functions in the widget options.

Would it make sense to replace the quoted line with `var options = opts` instead? Or to find a way to make this stringify->parse dance optional?

**Comment by yaronn** [comment]
Hi @algernon 

The goal was to make a quick deep copy. I have changed it to a smarter deep copy in the master version. Let me know if that works for you. Note next push to npm will be around the end of the month.

Yaron

**Comment by algernon** [comment]
Finally got around to upgrade my dependencies, and indeed, the current version on npm works for me. Awfully sorry for responding more than two years later!
