### ISSUE TITLE
TypeError: Cannot read property 'width' of null

### ISSUE THREAD

**Issue by evsign** [yaronn/blessed-contrib#57]
Hi. When i try to create ListTable in grid, application crashing with that error.
![ba0bxljc14r7my](https://cloud.githubusercontent.com/assets/7965780/8951710/ba54351c-35d8-11e5-8c5d-c07162c400ef.jpg)

```javascript
var accountList = mainGrid.set(1, 16, 6, 9, blessed.ListTable, {
	label: "Loaded Acounts",
	keys: true,
	fg: "white",
	selectedFg: "white",
	selectedBg: "blue",
	interactive: true,
	border: {type: "line", fg: "cyan"},
	scrollable: true
});

accountList.setData({
	headers: ["Login", "Password"],
	data: [["asdasd", "asdasd"], ["asdd", "asda"]]
});
```
How fix that problem? Maybe i do something wrong?

**Comment by kokarn** [comment]
Wow, I had the same issue but with Listbar. Ended up switching to List because I was unable to figure it out :/

**Comment by yaronn** [comment]
not sure yet why this happens but the following will work:

    var accountList = grid.set(0, 0, 8, 8, blessed.ListTable, {
        parent: screen, //add this
        //label: "Loaded Acounts",  //comment out
        //keys: true,  //comment out
        //everything else stays...
        ///...
    });

    //api gets an array of arrays
    accountList.setData(  
        [    ["asdasd", "asdasd"], ["asdd", "asda"] ]
    );

not sure if these changes are an option for you. (Note I might not have time to debug this further in the next few weeks, sorry)

**Comment by evsign** [comment]
Thank for reply, but unfortunately option parent: screen throw another error(
![8annknytnxbgao](https://cloud.githubusercontent.com/assets/7965780/8982761/ee310942-36cc-11e5-8c36-decc823c642e.jpg)

**Comment by yaronn** [comment]
Can you publish a minimal sample that produce this with the changes I
recommend before applied?

**Comment by evsign** [comment]
Like in start post and with parent option.

There is full code for representing this error:
```javascript
var blessed = require("blessed");
var screen = blessed.screen();
var contrib = require("blessed-contrib");

var mainGrid = new contrib.grid({rows: 30, cols: 30, screen: screen});

var accountList = mainGrid.set(1, 18, 17, 12, blessed.ListTable, {
    parent: screen,
    label: "Loaded accounts",
    keys: true,
    fg: "white",
    selectedFg: "white",
    selectedBg: "blue",
    interactive: true,
    border: {type: "line", fg: "cyan"},
    scrollable: true
});

accountList.focus();

accountList.setData(  
    [    ["asdasd", "asdasd"], ["asdd", "asda"] ]
);

screen.render();
```

**Comment by yaronn** [comment]
I was able to run this sample when commenting out the "label" property (not sure why yet).

**Comment by yaronn** [comment]
I think this is an issue with the blessed library since I was able to produce it even without the grid. check this: https://github.com/chjj/blessed/issues/160

**Comment by yaronn** [comment]
@evsign  this should be fixed with blessed@0.1.20 (same contrib version). can you verify that works for you?

**Comment by evsign** [comment]
@yaronn i do `npm update` and `npm upgrade` and unfortunately, i took another error(
![123123123](https://cloud.githubusercontent.com/assets/7965780/9012444/9f057398-37bd-11e5-9f53-0f9f66a6ffe6.jpg)

**Comment by yaronn** [comment]
Waiting for a long flight and don't have my pc to check this...

Does any code with blessed contrib fail? Even simple examples? Seems an
error with one of the dependencies which fails up front,  is there a way
for you to just upgrade blessed?

**Comment by evsign** [comment]
hmm. After i deleted node_modules dir and do `npm install` all have been working)

**Comment by yaronn** [comment]
This is great news!

**Comment by evsign** [comment]
@yaronn Thanks for help and fast replies)
