### ISSUE TITLE
Widget border line drawing error

### ISSUE THREAD

**Issue by JoeeGrigg** [yaronn/blessed-contrib#63]
Hi,

I have just tried installing this but when I run the example I get an error where the lines around each widget are letters rather than lines.

![Error Image](http://i.imgur.com/2SWnx2l.png)

I am running OSX El Capitan and using the font Monaco.

Any ideas anyone?

**Comment by yaronn** [comment]
Hi

Do you see the same issue with a simple blessed example?

    var blessed = require('blessed');
    var screen = blessed.screen();
    var box = blessed.box({
      top: 'center',
      left: 'center',
      width: '50%',
      height: '50%',
      content: 'Hello {bold}world{/bold}!',
      tags: true,
      border: {
        type: 'line'
      },
      style: {
        fg: 'white',
        bg: 'magenta',
        border: {
         fg: '#f0f0f0'
        },
        hover: {
          bg: 'green'
        }
      }
    });

    screen.append(box);
    screen.key(['escape', 'q', 'C-c'], function(ch, key) {
      return process.exit(0);
    });
    screen.render();

If so the question is more relevant to the blessed project.

You can also try with a different font (e.g. consolas).

It may also depend in the terminal software you use (iTerm2 works well).

**Comment by JoeeGrigg** [comment]
Hi

I am using iTerm2 and tried the consolas font but that doesn't seem to be fixing anything.

I have also tried your example and that seems to also be having the same problem.

As you mentioned I will take this question across to the blessed project and see if they have any ideas :smile:
