### ISSUE TITLE
grid.set is ok.. but, how to hide any widgets?

### ISSUE THREAD

**Issue by vicendominguez** [yaronn/blessed-contrib#64]
Hello guys!

Thank you for this amazing project. I love it. I have a question for you.

I am working with a grid, and it is ok. But i need to change my widgets because i am using a dynamic json to draw the widgets. I mean, i need to draw "x" number of bar widgets from a REST-API. If that json is sending me 3 nodes, then I need to draw three bar-widgets with the data. If that REST-API sends me twelve nodes, then I need to draw twelve. 

I can use grid.set to draw that widgets with a "for" or something similar but... if my new request has a number of nodes  **lower than** before one then i need to hide the widgets  painted in the screen (or something similar) because screen.render() doesn't clear the buffer with the painted widgets i had before.

So, is there any method to clear the screen buffer or to hide widgets in a grid?

Thx

**Comment by yaronn** [comment]
Check out how wopr does something similar:

https://github.com/yaronn/wopr/blob/master/lib/document-viewer.js#L52

**Comment by vicendominguez** [comment]
Good trick!! working for me. Thx my lord. :+1:

**Comment by yaronn** [comment]
cool :)
