### ISSUE TITLE
numYLabels doesn't affect number of labels

### ISSUE THREAD

**Issue by andrey-gvrd** [yaronn/blessed-contrib#71]
It seems like number of labels on Y axis for line chart is set at 5 and isn't affected by this option.

P.S.: Where can I look up all possible options for objects?

**Comment by yaronn** [comment]
Hi, please try again now with blessed-contrib@2.5.3 (just published with the fix). 

The goal is to have all settings in the README in each component section. Sometimes I may have missed some settings which you can usually find in the ctor of the relevant component (e.g. widgets/charts/line.js). If you see something missing please let me know.

Good luck!

**Comment by andrey-gvrd** [comment]
Thanks, that works now.
