### ISSUE TITLE
Color bleeding with line charts

### ISSUE THREAD

**Issue by andrey-gvrd** [yaronn/blessed-contrib#72]
Something that happens when plotting (float) data series with values in the same range. Unfortunately I couldn't easily copy data from logs for reproducibility, I can do that manually if needed. 

![color-bleeding](https://cloud.githubusercontent.com/assets/5842980/12036844/c26243fc-ae5a-11e5-8d2b-63248477e102.png)

A potential workaround would be to make the Y axis start from a non-zero value, is that currently possible?

**Comment by yaronn** [comment]
Try using the current master branch - I've added a property "minY" to the line chart. Let me know how it goes!

The error happens because dots that end up in the same character must have the same color, so to some extend such bleeding is unavoidable. Changing the chart height by 1-3 pixels might solve some bleeding issues (but introduce others).

**Comment by andrey-gvrd** [comment]
The example you posted does not work for me at all (I'm using `blessed-contrib@2.5.3 extraneous (git+https://github.com/yaronn/blessed-contrib.git#5583d6bb871718ef3d1e5a8255e5d8c3c2d3f30e)` -- pretty sure that is the version you mentioned).

Also the commit you submitted doesn't seem to modify the line chart object, but just adds an example, is that right?

**Comment by yaronn** [comment]
my bad, try now (use the master branch from github, not published in npm
yet).

On Wed, Dec 30, 2015 at 6:38 PM, andrey <notifications@github.com> wrote:

> The example you posted does not work for me at all (I'm using
> blessed-contrib@2.5.3 extraneous (git+
> https://github.com/yaronn/blessed-contrib.git#5583d6bb871718ef3d1e5a8255e5d8c3c2d3f30e
> ) -- pretty sure that is the version you mentioned).
>
> Also the commit you submitted doesn't seem to modify the line chart
> object, but just adds an example, is that right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yaronn/blessed-contrib/issues/72#issuecomment-168030578>
> .
>



-- 

I'm on Twitter (@YaronNaveh <http://twitter.com/#!/YaronNaveh>)

**Comment by andrey-gvrd** [comment]
Thanks, it works now.
