### ISSUE TITLE
the boader with qqqq?

### ISSUE THREAD

**Issue by zphj1987** [yaronn/blessed-contrib#75]
![image](https://cloud.githubusercontent.com/assets/2322061/12554713/cd2a327c-c3b8-11e5-9c26-0f83a504d2f0.png)

some one has the same problem? the boarder with qqqq or xxx

**Comment by zphj1987** [comment]
i run it on windows xshell, and myserver is centos7

**Comment by zphj1987** [comment]
the problem is with blessed ,i will find it

**Comment by wmhilton** [comment]
I had a very similar problem, with various shells on my Windows 7 computer. Adding this to the top of my file (before the requires) fixed the qqqq borders:
```
if (process.platform === 'win32') {
  process.env.TERM = 'windows-ansi'
}
```
