### ISSUE TITLE
Rate line color confusion

### ISSUE THREAD

**Issue by markmitton** [yaronn/blessed-contrib#77]
Hi

I am using a rate line to track 3 values. When the values are very close to each other the colors plotted seem to get confused. I understand when the values are the same only one color can be shown, but I have instances where the 2 lines diverge and both are the same color. Am I missing something here?

![screenshot from 2016-02-15 11 32 58](https://cloud.githubusercontent.com/assets/6764365/13044760/a06d36dc-d3d8-11e5-95ec-d23e6368b8d2.png)
![screenshot from 2016-02-15 11 35 16](https://cloud.githubusercontent.com/assets/6764365/13044761/a072b6e8-d3d8-11e5-91d7-92348e26f9d4.png)
![screenshot from 2016-02-15 11 37 56](https://cloud.githubusercontent.com/assets/6764365/13044762/a07540c0-d3d8-11e5-97db-a55889c440eb.png)

**Comment by yaronn** [comment]
Let's say that when you write characters in the terminal each character is one square. The barille font which is the base for blessed-contrib renders 2*4 dots (like the ones you see in the line) in a single character. But all dots of same character must have the same color. So when lines are close this will happen. If those lines are static you may get away with it by pushing the whole chart one pixel / percent up or down so the dots (might) be separated again. But there essence of this limitation still remains.

**Comment by markmitton** [comment]
Thanks Yaronn

Makes perfect sense. I was under the impression you could have different color dots in the same character.

Awesome library, Thank you!!
