### ISSUE TITLE
Cannot use 256 colors in donuts widget.

### ISSUE THREAD

**Issue by mvaladas** [yaronn/blessed-contrib#79]
As far as I can tell, you can only use 8 colors when drawing with drawille.

I can try and contribute to the repo so it supports 256 colors, but I cannot find the github repo for drawille-canvas-blessed-contrib.

If you tell me I can have a look and get more colors out of the canvas.

Cheers.

**Comment by yaronn** [comment]
it was in bitbucket so I have moved it here:
https://github.com/yaronn/drawille-canvas-blessed-contrib

would be amazing if you can get more colors in!

**Comment by mvaladas** [comment]
I'll give it a try tomorrow.

**Comment by mvaladas** [comment]
Had a very quick look at it seems I that the package controlling the color output is "ansi-term".
I'm trying to get it to work with https://github.com/jbnicolai/ansi-256-colors

Still not sure how to adapt the widgets to this new color system.
Either we enumerate the already known colors and support more advanced colors, or switch the color input options to accept ansi-256-colors codes and rgb values.

cheers.

**Comment by yaronn** [comment]
looks good! we need to have backward compatibility for existing users so it seems best to enumerate the known colors.

**Comment by mvaladas** [comment]
Okay. I almost have it.
I'm trying to get 256 colors support everywhere.
For that I need to do some changes to the ansi-term package.
You think you could move it from bitbucket also to githhub?

Cheers.

**Comment by yaronn** [comment]
Sure: https://github.com/yaronn/ansi-term

**Comment by mvaladas** [comment]
Finished.

I didn't do extensive testing. I just ran the example dashboard and it all seemed okay.

**Comment by mvaladas** [comment]
There seems to be something wrong with the line chart labels.
The color seems correct, but the label will not show correctly.

Will look into it.

**Comment by mvaladas** [comment]
Fixed it! You can pull changes.

**Comment by mvaladas** [comment]
Some examples of the dashboard with 256 colors
<img width="1434" alt="untitled 4" src="https://cloud.githubusercontent.com/assets/120122/13374863/a58b0542-dd90-11e5-9948-47041eed31c4.png">
<img width="1434" alt="untitled" src="https://cloud.githubusercontent.com/assets/120122/13374864/a5afa172-dd90-11e5-855b-148aa1d5ac64.png">
<img width="1434" alt="untitled 2" src="https://cloud.githubusercontent.com/assets/120122/13374865/a5afbc02-dd90-11e5-8b53-1e1da9aba747.png">

**Comment by yaronn** [comment]
This is so cool! I've merged this and also added your name to the readme, let me know if you want to link your name to some place. 

do you think you can add something very short in the readme about this feature? 

also wrt dashboard.js, it is impressive to add it random color capability, but I think the original palette is a good first impression for people trying blessed-contrib (random colors result can vary). Maybe we should revert it to use the fixed colors and add custom-color.js as a dedicated sample for this feature. What do you think?

**Comment by mvaladas** [comment]
Sure. The random color was just me trying the feature out, I agree that the original palette is good.
I'll write something for the Readme later tonight.

**Comment by yaronn** [comment]
I added a short description to the readme.

On Sun, Feb 28, 2016 at 9:17 AM, Miguel Valadas <notifications@github.com>
wrote:

> Sure. The random color was just me trying the feature out, I agree that
> the original palette is good.
> I'll write something for the Readme later tonight.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yaronn/blessed-contrib/issues/79#issuecomment-189809719>
> .
>



-- 

I'm on Twitter (@YaronNaveh <http://twitter.com/#!/YaronNaveh>)

**Comment by mvaladas** [comment]
Thank you. I had completely forgotten that I had to do it, sorry about that.

I'm closing the issue.

**Comment by yaronn** [comment]
no problem, great work on adding this capability.
