### ISSUE TITLE
Stacked Bar Chart's barCategory is blocked by border in grid

### ISSUE THREAD

**Issue by xiaoxinghu** [yaronn/blessed-contrib#82]
When mount stacked bar chart onto grid, the bar category is blocked by the border. Hiding the border helped but it should work with border.

With border:
![screen shot 2016-05-18 at 2 21 14 pm](https://cloud.githubusercontent.com/assets/1196745/15345529/f190d4be-1d03-11e6-94e5-5043704dc623.png)

Hiding border
![screen shot 2016-05-18 at 2 21 46 pm](https://cloud.githubusercontent.com/assets/1196745/15345528/f18b913e-1d03-11e6-9b7a-e312f828549e.png)

**Comment by solenwin2** [comment]
Readme_edit.
