### ISSUE TITLE
zoom in to see the difference between big numbers in line chart

### ISSUE THREAD

**Issue by SimonMonecke** [yaronn/blessed-contrib#86]
Hi,

it would be nice to have an auto zoom option.

I have numbers betweeen 2000 and 2050 and I can not see any difference between them in the line chart. Even if I set the minY option to 2000 I have a maxY value of 2760 and a horizontal line near the beaseline.

I suggest to provide to new option: 
autoZoom: {
  enabled: true,
  paddingBottom: 10, // minY is set to the min value of the provided numbers - 10
  paddingTop: 10 // maxY is set to the max value of the provided numbers - 10
}

Is this a good idea or do you have a better one to solve my problem. Maybe I missed an option.

Regards,
  Simon

**Comment by yaronn** [comment]
does setting maxY manually (like [this)](https://github.com/yaronn/blessed-contrib/blob/5da7f615da7f4343e93fec3295d19e612d887bc8/examples/dashboard.js#L90) make the chart look good? If so for now you can update the max Y either up front or every time you update the data.

**Comment by SimonMonecke** [comment]
I've tried to set maxY manually but this value was ignored.
I think the problem is that you take the largest number in the data array and multiply it with 1.2 twice. If this result is larger than the maxY value you ignore this option.

```
max = m*1.2;
max*=1.2
if (self.options.maxY) {
  return Math.max(max, self.options.maxY)
}
```

Maybe this is a bug and you want to apply Math.min()?
If this is the case I can follow your advice and update maxY and many manually after every update of my data ;)

Regards,
  Simon

**Comment by yaronn** [comment]
so if you hard code your maxY in blessed-contrib source (just for testing) you see the desired output?

**Comment by SimonMonecke** [comment]
Hi,

yes! If I modify line.js
```
max = m*1.2;
max*=1.2
max=2100 // HARDCODED
if (self.options.maxY) {
  return Math.max(max, self.options.maxY)
}
```
or
```
max = m*1.2;
max*=1.2
if (self.options.maxY) {
  return Math.min(max, self.options.maxY) // change Math.max to Math.min
}
```
I see the correct result:
![terminal_008](https://cloud.githubusercontent.com/assets/4587790/17890378/f387aad0-6935-11e6-8c56-0b86f548a926.png)

Chart without modification of line.js:
![terminal_009](https://cloud.githubusercontent.com/assets/4587790/17890403/17cbf766-6936-11e6-9145-de7943a52204.png)

**Comment by thomasdondorf** [comment]
I don't think using Math.min is the right choice. I added a pull request, which takes any value you provide as maxY. The whole point of providing a maxY is that you do not want the library to use the calculated value. So I think this is the only correct solution.

However, while I am writing this, it comes to my mind that maybe I should have added a check for maxY > minY?
